application: hyptools
version: 3
runtime: python
api_version: 1

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /
  script: index.py

- url: /index\.html
  script: index.py

- url: /(battle_reports|present_fleets|hivemind)
  script: \1/index.py

- url: /hivemind/(update|search|login)
  script: /hivemind/index.py

- url: /.*
  script: notfound.py
